server:
  port: 8081

spring:
  application:
    name: auth-service
  jpa:
    show_sql: false
    database: MYSQL
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/mysql
    username: root
    password: dbpass

