version: '3.1'

services:
  adminer:
    image: adminer
    ports:
      - 8080:8080

  dbMysql:
    image: mysql:8.0.3
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: dbpass
      MYSQL_DATABASE: mydb

  eureka:
    image: springcloud/eureka
    ports:
      - 8761:8761